### ISSUE TITLE
Having trouble getting the node client to run...

### ISSUE THREAD

**Issue by pavoni** [marcosscriven/loop#2]
Have added my secret and serial codes.

````
❯ npm install
npm WARN EPACKAGEJSON loop@1.0.0 No repository field.

❯ npm start

> loop@1.0.0 start /Users/greg/ha-python/loop
> node loop.js

````
But then it looks look the process terminates.

Sorry if I'm doing something foolish -

**Comment by pavoni** [comment]
I stole your ideas to make a Python api.

https://github.com/pavoni/pyloopenergy

Thanks for all the work.

Leaving this open in case you want to fix - but not urgent in my case.

**Comment by marcosscriven** [comment]
Sorry - only just saw this. Thanks for reporting, the start script in ```package.json``` was pointing to the wrong file.
Glad to hear you've made a Python version - that's my usual goto for this kind of thing, but in this case I wanted it to run easily in the browser.
